// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoScanEpisodes() {
  return window['go']['main']['App']['AutoScanEpisodes']();
}

export function AutoScanFolder() {
  return window['go']['main']['App']['AutoScanFolder']();
}

export function ChangeCover(arg1) {
  return window['go']['main']['App']['ChangeCover'](arg1);
}

export function CheckTitleExists(arg1, arg2) {
  return window['go']['main']['App']['CheckTitleExists'](arg1, arg2);
}

export function ClearPlaybackHistory() {
  return window['go']['main']['App']['ClearPlaybackHistory']();
}

export function DeleteVideo(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteVideo'](arg1, arg2, arg3);
}

export function GetDuration(arg1) {
  return window['go']['main']['App']['GetDuration'](arg1);
}

export function GetFavoriteVideos() {
  return window['go']['main']['App']['GetFavoriteVideos']();
}

export function GetLastPlayedVideos() {
  return window['go']['main']['App']['GetLastPlayedVideos']();
}

export function GetVideoCount() {
  return window['go']['main']['App']['GetVideoCount']();
}

export function GetVideos() {
  return window['go']['main']['App']['GetVideos']();
}

export function ImportVideo() {
  return window['go']['main']['App']['ImportVideo']();
}

export function MarkAsPlayed(arg1) {
  return window['go']['main']['App']['MarkAsPlayed'](arg1);
}

export function MoveToEpisodeFolder() {
  return window['go']['main']['App']['MoveToEpisodeFolder']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenVideo(arg1) {
  return window['go']['main']['App']['OpenVideo'](arg1);
}

export function RenameVideo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RenameVideo'](arg1, arg2, arg3, arg4);
}

export function SaveVideoEdit(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SaveVideoEdit'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}

export function UpdateArtist(arg1, arg2) {
  return window['go']['main']['App']['UpdateArtist'](arg1, arg2);
}

export function UpdateCover(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateCover'](arg1, arg2, arg3);
}

export function UpdateScreenshotPath(arg1, arg2) {
  return window['go']['main']['App']['UpdateScreenshotPath'](arg1, arg2);
}

export function UpdateVideoData(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateVideoData'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateVideoLocation(arg1) {
  return window['go']['main']['App']['UpdateVideoLocation'](arg1);
}
