// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeCover(arg1:number):Promise<void>;

export function DeleteVideo(arg1:number,arg2:string,arg3:string):Promise<void>;

export function GetDuration(arg1:string):Promise<string>;

export function GetVideos():Promise<Array<Record<string, any>>>;

export function ImportVideo():Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenVideo(arg1:string):Promise<void>;

export function RenameVideo(arg1:number,arg2:string,arg3:string):Promise<void>;

export function SaveVideoEdit(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function SelectFolder():Promise<string>;

export function UpdateArtist(arg1:number,arg2:string):Promise<void>;

export function UpdateCover(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateScreenshotPath(arg1:number,arg2:string):Promise<void>;

export function UpdateVideoData(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function UpdateVideoLocation(arg1:number):Promise<string>;
