// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AutoScanEpisodes():Promise<void>;

export function AutoScanFolder():Promise<number>;

export function ChangeCover(arg1:number):Promise<void>;

export function CheckTitleExists(arg1:string,arg2:number):Promise<boolean>;

export function ClearPlaybackHistory():Promise<void>;

export function DeleteVideo(arg1:number,arg2:string,arg3:string):Promise<void>;

export function GetDuration(arg1:string):Promise<string>;

export function GetFavoriteVideos():Promise<Array<main.Video>>;

export function GetLastPlayedVideos():Promise<Array<main.Video>>;

export function GetVideoCount():Promise<number>;

export function GetVideos():Promise<Array<main.Video>>;

export function ImportVideo():Promise<void>;

export function MarkAsPlayed(arg1:number):Promise<void>;

export function MoveToEpisodeFolder():Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenVideo(arg1:string):Promise<void>;

export function RenameVideo(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveVideoEdit(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function SelectFolder():Promise<string>;

export function ToggleFavorite(arg1:number):Promise<void>;

export function UpdateArtist(arg1:number,arg2:string):Promise<void>;

export function UpdateCover(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateScreenshotPath(arg1:number,arg2:string):Promise<void>;

export function UpdateVideoData(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function UpdateVideoLocation(arg1:number):Promise<string>;
